# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../MockObjects/LibraryMock.h \
    ../../../Plugins/SampleGenerator/SampleGenerator.h \
    ../../../Plugins/SampleGenerator/SampleParser.h
SOURCES += ./tst_SampleGenerator.cpp \
    ../../MockObjects/LibraryMock.cpp \
    ../../../Plugins/SampleGenerator/SampleParser.cpp \
    ../../../Plugins/SampleGenerator/SampleGenerator.cpp
